### ISSUE TITLE
Adding functionality to shown current question number.

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/hugs_for_bugs#6]
As you can check in website that in depression test several question will be asked from user.
You need to add a **counter** that will keep track of **remaining** and **current** question number.

![B-well_Depression-Test](https://user-images.githubusercontent.com/78257493/135819481-ecb1e7ff-8e0b-4cdf-bc82-1cd6e55b3eb0.png)

You can add the counters below the **next button** and you can also reduce size of **next button**.

_If you want to add more features or encounters bugs. feel free to raise issues._

**Comment by pavankalyan-codes** [comment]
Hey! I have made changes for this and made a [PR](https://github.com/Deepak91168/hugs_for_bugs/pull/7). Please merge changes if everything looks fine.
